### ISSUE TITLE
Mainnet checklist

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/ethereum-alarm-clock#150]
Audit Fixes
-----------
- [X] Make recommended changes #151 #155 

Features
--------
 - [x] Floating gas price for execution #149 
 - [X] Update to most recent version of minimal proxy bytecode #153 
 - [X] Killswitch #158 

Misc
----
 - [X] Remove Populus tests #145 #152 
 - [ ] Update Documentation

**Comment by lsaether** [comment]
Deployed.
